[package]
name = "rust_pdf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.10.0"
flate2 = "1.0.26"
log = "0.4.17"
nom = "7.1.3"
num-traits = "0.2.15"
regex = "1.8.1"
